---
apiVersion: projectriff.io/v1alpha1
kind: Invoker
metadata:
  name: python2
spec:
  version: 0.0.7-snapshot
  matchers:
  - "*.py"
  handler:
    default: "{{ .FunctionName }}"
    description: the name of the function handler
  functionTemplate:
    spec:
      protocol: grpc
  files:
  - path: Dockerfile
    template: |
      FROM projectriff/python2-function-invoker:{{.InvokerVersion}}
      ARG FUNCTION_MODULE={{.ArtifactBase}}
      ARG FUNCTION_HANDLER={{.Handler}}
      ADD ./{{.ArtifactBase}} /
      {{- if .FileExists "requirements.txt" }}
      ADD ./requirements.txt /
      RUN  pip install --upgrade pip && pip install -r /requirements.txt
      {{- end }}
      ENV FUNCTION_URI file:///${FUNCTION_MODULE}?handler=${FUNCTION_HANDLER}
  doc: |
    {{.Process}} the function based on the function source code specified as the filename, handler
    name, artifact and version specified for the function image repository and tag.
    
    For example, type:
    
        riff {{.Command}} -i words -n uppercase --handler=process
    
    to {{.Result}}.
