# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: function.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='function.proto',
  package='function',
  syntax='proto3',
  serialized_pb=_b('\n\x0e\x66unction.proto\x12\x08\x66unction\"\xb9\x01\n\x07Message\x12\x0f\n\x07payload\x18\x01 \x01(\x0c\x12/\n\x07headers\x18\x02 \x03(\x0b\x32\x1e.function.Message.HeadersEntry\x1a\x1d\n\x0bHeaderValue\x12\x0e\n\x06values\x18\x01 \x03(\t\x1aM\n\x0cHeadersEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12,\n\x05value\x18\x02 \x01(\x0b\x32\x1d.function.Message.HeaderValue:\x02\x38\x01\x32\x45\n\x0fMessageFunction\x12\x32\n\x04\x43\x61ll\x12\x11.function.Message\x1a\x11.function.Message\"\x00(\x01\x30\x01\x62\x06proto3')
)




_MESSAGE_HEADERVALUE = _descriptor.Descriptor(
  name='HeaderValue',
  full_name='function.Message.HeaderValue',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='values', full_name='function.Message.HeaderValue.values', index=0,
      number=1, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=106,
  serialized_end=135,
)

_MESSAGE_HEADERSENTRY = _descriptor.Descriptor(
  name='HeadersEntry',
  full_name='function.Message.HeadersEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='function.Message.HeadersEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='value', full_name='function.Message.HeadersEntry.value', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=_descriptor._ParseOptions(descriptor_pb2.MessageOptions(), _b('8\001')),
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=137,
  serialized_end=214,
)

_MESSAGE = _descriptor.Descriptor(
  name='Message',
  full_name='function.Message',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='payload', full_name='function.Message.payload', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='headers', full_name='function.Message.headers', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_MESSAGE_HEADERVALUE, _MESSAGE_HEADERSENTRY, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=29,
  serialized_end=214,
)

_MESSAGE_HEADERVALUE.containing_type = _MESSAGE
_MESSAGE_HEADERSENTRY.fields_by_name['value'].message_type = _MESSAGE_HEADERVALUE
_MESSAGE_HEADERSENTRY.containing_type = _MESSAGE
_MESSAGE.fields_by_name['headers'].message_type = _MESSAGE_HEADERSENTRY
DESCRIPTOR.message_types_by_name['Message'] = _MESSAGE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Message = _reflection.GeneratedProtocolMessageType('Message', (_message.Message,), dict(

  HeaderValue = _reflection.GeneratedProtocolMessageType('HeaderValue', (_message.Message,), dict(
    DESCRIPTOR = _MESSAGE_HEADERVALUE,
    __module__ = 'function_pb2'
    # @@protoc_insertion_point(class_scope:function.Message.HeaderValue)
    ))
  ,

  HeadersEntry = _reflection.GeneratedProtocolMessageType('HeadersEntry', (_message.Message,), dict(
    DESCRIPTOR = _MESSAGE_HEADERSENTRY,
    __module__ = 'function_pb2'
    # @@protoc_insertion_point(class_scope:function.Message.HeadersEntry)
    ))
  ,
  DESCRIPTOR = _MESSAGE,
  __module__ = 'function_pb2'
  # @@protoc_insertion_point(class_scope:function.Message)
  ))
_sym_db.RegisterMessage(Message)
_sym_db.RegisterMessage(Message.HeaderValue)
_sym_db.RegisterMessage(Message.HeadersEntry)


_MESSAGE_HEADERSENTRY.has_options = True
_MESSAGE_HEADERSENTRY._options = _descriptor._ParseOptions(descriptor_pb2.MessageOptions(), _b('8\001'))

_MESSAGEFUNCTION = _descriptor.ServiceDescriptor(
  name='MessageFunction',
  full_name='function.MessageFunction',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=216,
  serialized_end=285,
  methods=[
  _descriptor.MethodDescriptor(
    name='Call',
    full_name='function.MessageFunction.Call',
    index=0,
    containing_service=None,
    input_type=_MESSAGE,
    output_type=_MESSAGE,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_MESSAGEFUNCTION)

DESCRIPTOR.services_by_name['MessageFunction'] = _MESSAGEFUNCTION

try:
  # THESE ELEMENTS WILL BE DEPRECATED.
  # Please use the generated *_pb2_grpc.py files instead.
  import grpc
  from grpc.beta import implementations as beta_implementations
  from grpc.beta import interfaces as beta_interfaces
  from grpc.framework.common import cardinality
  from grpc.framework.interfaces.face import utilities as face_utilities


  class MessageFunctionStub(object):
    # missing associated documentation comment in .proto file
    pass

    def __init__(self, channel):
      """Constructor.

      Args:
        channel: A grpc.Channel.
      """
      self.Call = channel.stream_stream(
          '/function.MessageFunction/Call',
          request_serializer=Message.SerializeToString,
          response_deserializer=Message.FromString,
          )


  class MessageFunctionServicer(object):
    # missing associated documentation comment in .proto file
    pass

    def Call(self, request_iterator, context):
      # missing associated documentation comment in .proto file
      pass
      context.set_code(grpc.StatusCode.UNIMPLEMENTED)
      context.set_details('Method not implemented!')
      raise NotImplementedError('Method not implemented!')


  def add_MessageFunctionServicer_to_server(servicer, server):
    rpc_method_handlers = {
        'Call': grpc.stream_stream_rpc_method_handler(
            servicer.Call,
            request_deserializer=Message.FromString,
            response_serializer=Message.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        'function.MessageFunction', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


  class BetaMessageFunctionServicer(object):
    """The Beta API is deprecated for 0.15.0 and later.

    It is recommended to use the GA API (classes and functions in this
    file not marked beta) for all further purposes. This class was generated
    only to ease transition from grpcio<0.15.0 to grpcio>=0.15.0."""
    # missing associated documentation comment in .proto file
    pass
    def Call(self, request_iterator, context):
      # missing associated documentation comment in .proto file
      pass
      context.code(beta_interfaces.StatusCode.UNIMPLEMENTED)


  class BetaMessageFunctionStub(object):
    """The Beta API is deprecated for 0.15.0 and later.

    It is recommended to use the GA API (classes and functions in this
    file not marked beta) for all further purposes. This class was generated
    only to ease transition from grpcio<0.15.0 to grpcio>=0.15.0."""
    # missing associated documentation comment in .proto file
    pass
    def Call(self, request_iterator, timeout, metadata=None, with_call=False, protocol_options=None):
      # missing associated documentation comment in .proto file
      pass
      raise NotImplementedError()


  def beta_create_MessageFunction_server(servicer, pool=None, pool_size=None, default_timeout=None, maximum_timeout=None):
    """The Beta API is deprecated for 0.15.0 and later.

    It is recommended to use the GA API (classes and functions in this
    file not marked beta) for all further purposes. This function was
    generated only to ease transition from grpcio<0.15.0 to grpcio>=0.15.0"""
    request_deserializers = {
      ('function.MessageFunction', 'Call'): Message.FromString,
    }
    response_serializers = {
      ('function.MessageFunction', 'Call'): Message.SerializeToString,
    }
    method_implementations = {
      ('function.MessageFunction', 'Call'): face_utilities.stream_stream_inline(servicer.Call),
    }
    server_options = beta_implementations.server_options(request_deserializers=request_deserializers, response_serializers=response_serializers, thread_pool=pool, thread_pool_size=pool_size, default_timeout=default_timeout, maximum_timeout=maximum_timeout)
    return beta_implementations.server(method_implementations, options=server_options)


  def beta_create_MessageFunction_stub(channel, host=None, metadata_transformer=None, pool=None, pool_size=None):
    """The Beta API is deprecated for 0.15.0 and later.

    It is recommended to use the GA API (classes and functions in this
    file not marked beta) for all further purposes. This function was
    generated only to ease transition from grpcio<0.15.0 to grpcio>=0.15.0"""
    request_serializers = {
      ('function.MessageFunction', 'Call'): Message.SerializeToString,
    }
    response_deserializers = {
      ('function.MessageFunction', 'Call'): Message.FromString,
    }
    cardinalities = {
      'Call': cardinality.Cardinality.STREAM_STREAM,
    }
    stub_options = beta_implementations.stub_options(host=host, metadata_transformer=metadata_transformer, request_serializers=request_serializers, response_deserializers=response_deserializers, thread_pool=pool, thread_pool_size=pool_size)
    return beta_implementations.dynamic_stub(channel, 'function.MessageFunction', cardinalities, options=stub_options)
except ImportError:
  pass
# @@protoc_insertion_point(module_scope)
